# O pacote react-scripts na versão 3.4.1 utilizada no frontend externo
# possui um bug que não permite execução normal no docker:
# https://github.com/facebook/create-react-app/issues/8688
# Para contornar, adicionamos o tty: true
# Vide issue https://github.com/CMCuritiba/processo_eletronico/issues/302

version: "3.8"
services:
  backend:
    image: cmc/spa2api
    ports:
      - "3002:3002"
    dns:
      - dns1
      - dns2
    networks:
      - local_network
    volumes:
      - type: volume
        source: backend_logs
        target: /var/log/spa2-api/
      - type: volume
        source: backend_files
        target: /opt/spa2-api/arquivos/
    tty: true

  frontend:
    image: cmc/spa2
    ports:
      - "3000:3000"
    networks:
      - local_network
    tty: true

  contab:
    image: cmc/spa2-contab
    ports:
      - "3010:3000"
    networks:
      - local_network
    tty: true

  externo:
    image: cmc/spa2-ext
    ports:
      - "3020:3000"
    networks:
      - local_network
    tty: true

  redis:
    image: redis:alpine
    networks:
      - local_network

networks:
  local_network:
    driver: overlay
    ipam:
      config:
        - subnet: 10.12.0.0/24


volumes:
  backend_logs:
  backend_files: