version: "3.1"
services:
    backend:
        image: cmc/spa2api
        ports:
            - "3002:3002"
    frontend:
        image: cmc/spa2
        ports:
            - "3000:3000"
    redis:
        image: redis:alpine
        ports:
            - '6379:6379'