version: "3.1"
services:
    db-spa2:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_PASSWORD: spa2
            POSTGRES_USER: postgres
            POSTGRES_DB: spa2_local
        ports:
            - "5432:5432"
