'use strict';

module.exports = {
    up: async(queryInterface, Sequelize) => {
        await queryInterface.bulkInsert(
            { tableName: 'banco', schema: 'spa2' },
            [
                { ban_id: 1, ban_numero: '001', ban_nome: 'BCO DO BRASIL S.A.(001)' },
                { ban_id: 2, ban_numero: '070', ban_nome: 'BRB - BCO DE BRASILIA S.A.(070)' },
                { ban_id: 3, ban_numero: '272', ban_nome: 'AGK CC S.A.(272)' },
                { ban_id: 4, ban_numero: '136', ban_nome: 'UNICRED(136)' },
                { ban_id: 5, ban_numero: '104', ban_nome: 'CAIXA ECONOMICA FEDERAL(104)' },
                { ban_id: 6, ban_numero: '077', ban_nome: 'BANCO INTER(077)' },
                { ban_id: 7, ban_numero: '741', ban_nome: 'BCO RIBEIRAO PRETO S.A.(741)' },
                { ban_id: 8, ban_numero: '330', ban_nome: 'BANCO BARI S.A.(330)' },
                { ban_id: 9, ban_numero: '739', ban_nome: 'BCO CETELEM S.A.(739)' },
                { ban_id: 10, ban_numero: '743', ban_nome: 'BANCO SEMEAR(743)' },
                { ban_id: 11, ban_numero: '100', ban_nome: 'PLANNER CV S.A.(100)' },
                { ban_id: 12, ban_numero: '096', ban_nome: 'BCO B3 S.A.(096)' },
                { ban_id: 13, ban_numero: '747', ban_nome: 'BCO RABOBANK INTL BRASIL S.A.(747)' },
                { ban_id: 14, ban_numero: '362', ban_nome: 'CIELO S.A.(362)' },
                { ban_id: 15, ban_numero: '322', ban_nome: 'CCR DE ABELARDO LUZ(322)' },
                { ban_id: 16, ban_numero: '748', ban_nome: 'BCO COOPERATIVO SICREDI S.A.(748)' },
                { ban_id: 17, ban_numero: '350', ban_nome: 'CREHNOR LARANJEIRAS(350)' },
                { ban_id: 18, ban_numero: '752', ban_nome: 'BCO BNP PARIBAS BRASIL S A(752)' },
                { ban_id: 19, ban_numero: '091', ban_nome: 'CCCM UNICRED CENTRAL RS(091)' },
                { ban_id: 20, ban_numero: '379', ban_nome: 'CECM COOPERFORTE(379)' },
                { ban_id: 21, ban_numero: '399', ban_nome: 'KIRTON BANK(399)' },
                { ban_id: 22, ban_numero: '108', ban_nome: 'PORTOCRED S.A. - CFI(108)' },
                { ban_id: 23, ban_numero: '756', ban_nome: 'BANCOOB(756)' },
                { ban_id: 24, ban_numero: '360', ban_nome: 'TRINUS CAPITAL DTVM(360)' },
                { ban_id: 25, ban_numero: '757', ban_nome: 'BCO KEB HANA DO BRASIL S.A.(757)' },
                { ban_id: 26, ban_numero: '102', ban_nome: 'XP INVESTIMENTOS CCTVM S/A(102)' },
                { ban_id: 27, ban_numero: '084', ban_nome: 'UNIPRIME NORTE DO PARANÁ - CC(084)' },
                { ban_id: 28, ban_numero: '180', ban_nome: 'CM CAPITAL MARKETS CCTVM LTDA(180)' },
                { ban_id: 29, ban_numero: '066', ban_nome: 'BCO MORGAN STANLEY S.A.(066)' },
                { ban_id: 30, ban_numero: '015', ban_nome: 'UBS BRASIL CCTVM S.A.(015)' },
                { ban_id: 31, ban_numero: '143', ban_nome: 'TREVISO CC S.A.(143)' },
                { ban_id: 32, ban_numero: '062', ban_nome: 'HIPERCARD BM S.A.(062)' },
                { ban_id: 33, ban_numero: '074', ban_nome: 'BCO. J.SAFRA S.A.(074)' },
                { ban_id: 34, ban_numero: '099', ban_nome: 'UNIPRIME CENTRAL CCC LTDA.(099)' },
                { ban_id: 35, ban_numero: '387', ban_nome: 'BCO TOYOTA DO BRASIL S.A.(387)' },
                { ban_id: 36, ban_numero: '326', ban_nome: 'PARATI - CFI S.A.(326)' },
                { ban_id: 37, ban_numero: '025', ban_nome: 'BCO ALFA S.A.(025)' },
                { ban_id: 38, ban_numero: '315', ban_nome: 'PI DTVM S.A.(315)' },
                { ban_id: 39, ban_numero: '075', ban_nome: 'BCO ABN AMRO S.A.(075)' },
                { ban_id: 40, ban_numero: '040', ban_nome: 'BCO CARGILL S.A.(040)' },
                { ban_id: 41, ban_numero: '307', ban_nome: 'TERRA INVESTIMENTOS DTVM(307)' },
                { ban_id: 42, ban_numero: '190', ban_nome: 'SERVICOOP(190)' },
                { ban_id: 43, ban_numero: '296', ban_nome: 'VISION S.A. CC(296)' },
                { ban_id: 44, ban_numero: '063', ban_nome: 'BANCO BRADESCARD(063)' },
                { ban_id: 45, ban_numero: '191', ban_nome: 'NOVA FUTURA CTVM LTDA.(191)' },
                { ban_id: 46, ban_numero: '382', ban_nome: 'FIDUCIA SCMEPP LTDA(382)' },
                { ban_id: 47, ban_numero: '064', ban_nome: 'GOLDMAN SACHS DO BRASIL BM S.A(064)' },
                { ban_id: 48, ban_numero: '097', ban_nome: 'CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.(097)' },
                { ban_id: 49, ban_numero: '016', ban_nome: 'SICOOB CREDITRAN(016)' },
                { ban_id: 50, ban_numero: '299', ban_nome: 'SOROCRED CFI S.A.(299)' },
                { ban_id: 51, ban_numero: '012', ban_nome: 'BANCO INBURSA(012)' },
                { ban_id: 52, ban_numero: '003', ban_nome: 'BCO DA AMAZONIA S.A.(003)' },
                { ban_id: 53, ban_numero: '060', ban_nome: 'CONFIDENCE CC S.A.(060)' },
                { ban_id: 54, ban_numero: '037', ban_nome: 'BCO DO EST. DO PA S.A.(037)' },
                { ban_id: 55, ban_numero: '359', ban_nome: 'ZEMA CFI S/A(359)' },
                { ban_id: 56, ban_numero: '159', ban_nome: 'CASA CREDITO S.A. SCM(159)' },
                { ban_id: 57, ban_numero: '085', ban_nome: 'COOP CENTRAL AILOS(085)' },
                { ban_id: 58, ban_numero: '114', ban_nome: 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO(114)' },
                { ban_id: 59, ban_numero: '036', ban_nome: 'BCO BBI S.A.(036)' },
                { ban_id: 60, ban_numero: '394', ban_nome: 'BCO BRADESCO FINANC. S.A.(394)' },
                { ban_id: 61, ban_numero: '004', ban_nome: 'BCO DO NORDESTE DO BRASIL S.A.(004)' },
                { ban_id: 62, ban_numero: '320', ban_nome: 'BCO CCB BRASIL S.A.(320)' },
                { ban_id: 63, ban_numero: '189', ban_nome: 'HS FINANCEIRA(189)' },
                { ban_id: 64, ban_numero: '105', ban_nome: 'LECCA CFI S.A.(105)' },
                { ban_id: 65, ban_numero: '076', ban_nome: 'BCO KDB BRASIL S.A.(076)' },
                { ban_id: 66, ban_numero: '082', ban_nome: 'BANCO TOPÁZIO S.A.(082)' },
                { ban_id: 67, ban_numero: '286', ban_nome: 'CCR DE OURO(286)' },
                { ban_id: 68, ban_numero: '093', ban_nome: 'POLOCRED SCMEPP LTDA.(093)' },
                { ban_id: 69, ban_numero: '391', ban_nome: 'CCR DE IBIAM(391)' },
                { ban_id: 70, ban_numero: '273', ban_nome: 'CCR DE SÃO MIGUEL DO OESTE(273)' },
                { ban_id: 71, ban_numero: '368', ban_nome: 'BCO CSF S.A.(368)' },
                { ban_id: 72, ban_numero: '290', ban_nome: 'PAGSEGURO(290)' },
                { ban_id: 73, ban_numero: '259', ban_nome: 'MONEYCORP BCO DE CÂMBIO S.A.(259)' },
                { ban_id: 74, ban_numero: '364', ban_nome: 'GERENCIANET PAGTOS BRASIL LTDA(364)' },
                { ban_id: 75, ban_numero: '157', ban_nome: 'ICAP DO BRASIL CTVM LTDA.(157)' },
                { ban_id: 76, ban_numero: '183', ban_nome: 'SOCRED SA - SCMEPP(183)' },
                { ban_id: 77, ban_numero: '014', ban_nome: 'STATE STREET BR S.A. BCO COMERCIAL(014)' },
                { ban_id: 78, ban_numero: '130', ban_nome: 'CARUANA SCFI(130)' },
                { ban_id: 79, ban_numero: '127', ban_nome: 'CODEPE CVC S.A.(127)' },
                { ban_id: 80, ban_numero: '079', ban_nome: 'BCO ORIGINAL DO AGRO S/A(079)' },
                { ban_id: 81, ban_numero: '340', ban_nome: 'SUPER PAGAMENTOS E ADMINISTRACAO DE MEIOS ELETRONICOS S.A.(340)' },
                { ban_id: 82, ban_numero: '081', ban_nome: 'BANCOSEGURO S.A.(081)' },
                { ban_id: 83, ban_numero: '133', ban_nome: 'CRESOL CONFEDERAÇÃO(133)' },
                { ban_id: 84, ban_numero: '323', ban_nome: 'MERCADO PAGO(323)' },
                { ban_id: 85, ban_numero: '121', ban_nome: 'BCO AGIBANK S.A.(121)' },
                { ban_id: 86, ban_numero: '083', ban_nome: 'BCO DA CHINA BRASIL S.A.(083)' },
                { ban_id: 87, ban_numero: '138', ban_nome: 'GET MONEY CC LTDA(138)' },
                { ban_id: 88, ban_numero: '024', ban_nome: 'BCO BANDEPE S.A.(024)' },
                { ban_id: 89, ban_numero: '088', ban_nome: 'BANCO RANDON S.A.(088)' },
                { ban_id: 90, ban_numero: '319', ban_nome: 'OM DTVM LTDA(319)' },
                { ban_id: 91, ban_numero: '274', ban_nome: 'MONEY PLUS SCMEPP LTDA(274)' },
                { ban_id: 92, ban_numero: '095', ban_nome: 'TRAVELEX BANCO DE CÂMBIO S.A.(095)' },
                { ban_id: 93, ban_numero: '094', ban_nome: 'BANCO FINAXIS(094)' },
                { ban_id: 94, ban_numero: '276', ban_nome: 'SENFF S.A. - CFI(276)' },
                { ban_id: 95, ban_numero: '092', ban_nome: 'BRK S.A. CFI(092)' },
                { ban_id: 96, ban_numero: '047', ban_nome: 'BCO DO EST. DE SE S.A.(047)' },
                { ban_id: 97, ban_numero: '144', ban_nome: 'BEXS BCO DE CAMBIO S.A.(144)' },
                { ban_id: 98, ban_numero: '332', ban_nome: 'ACESSO SOLUCOES PAGAMENTO SA(332)' },
                { ban_id: 99, ban_numero: '126', ban_nome: 'BR PARTNERS BI(126)' },
                { ban_id: 100, ban_numero: '325', ban_nome: 'ÓRAMA DTVM S.A.(325)' },
                { ban_id: 101, ban_numero: '301', ban_nome: 'BPP IP S.A.(301)' },
                { ban_id: 102, ban_numero: '173', ban_nome: 'BRL TRUST DTVM SA(173)' },
                { ban_id: 103, ban_numero: '331', ban_nome: 'FRAM CAPITAL DTVM S.A.(331)' },
                { ban_id: 104, ban_numero: '119', ban_nome: 'BCO WESTERN UNION(119)' },
                { ban_id: 105, ban_numero: '396', ban_nome: 'HUB PAGAMENTOS(396)' },
                { ban_id: 106, ban_numero: '309', ban_nome: 'CAMBIONET CC LTDA(309)' },
                { ban_id: 107, ban_numero: '254', ban_nome: 'PARANA BCO S.A.(254)' },
                { ban_id: 108, ban_numero: '268', ban_nome: 'BARI CIA HIPOTECÁRIA(268)' },
                { ban_id: 109, ban_numero: '107', ban_nome: 'BCO BOCOM BBM S.A.(107)' },
                { ban_id: 110, ban_numero: '412', ban_nome: 'BCO CAPITAL S.A.(412)' },
                { ban_id: 111, ban_numero: '124', ban_nome: 'BCO WOORI BANK DO BRASIL S.A.(124)' },
                { ban_id: 112, ban_numero: '149', ban_nome: 'FACTA S.A. CFI(149)' },
                { ban_id: 113, ban_numero: '197', ban_nome: 'STONE PAGAMENTOS S.A.(197)' },
                { ban_id: 114, ban_numero: '313', ban_nome: 'AMAZÔNIA CC LTDA.(313)' },
                { ban_id: 115, ban_numero: '142', ban_nome: 'BROKER BRASIL CC LTDA.(142)' },
                { ban_id: 116, ban_numero: '389', ban_nome: 'BCO MERCANTIL DO BRASIL S.A.(389)' },
                { ban_id: 117, ban_numero: '184', ban_nome: 'BCO ITAÚ BBA S.A.(184)' },
                { ban_id: 118, ban_numero: '634', ban_nome: 'BCO TRIANGULO S.A.(634)' },
                { ban_id: 119, ban_numero: '545', ban_nome: 'SENSO CCVM S.A.(545)' },
                { ban_id: 120, ban_numero: '132', ban_nome: 'ICBC DO BRASIL BM S.A.(132)' },
                { ban_id: 121, ban_numero: '298', ban_nome: 'VIPS CC LTDA.(298)' },
                { ban_id: 122, ban_numero: '321', ban_nome: 'CREFAZ SCMEPP LTDA(321)' },
                { ban_id: 123, ban_numero: '260', ban_nome: 'NU PAGAMENTOS S.A.(260)' },
                { ban_id: 124, ban_numero: '129', ban_nome: 'UBS BRASIL BI S.A.(129)' },
                { ban_id: 125, ban_numero: '128', ban_nome: 'MS BANK S.A. BCO DE CÂMBIO(128)' },
                { ban_id: 126, ban_numero: '194', ban_nome: 'PARMETAL DTVM LTDA(194)' },
                { ban_id: 127, ban_numero: '383', ban_nome: 'JUNO(383)' },
                { ban_id: 128, ban_numero: '310', ban_nome: 'VORTX DTVM LTDA.(310)' },
                { ban_id: 129, ban_numero: '163', ban_nome: 'COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO(163)' },
                { ban_id: 130, ban_numero: '280', ban_nome: 'AVISTA S.A. CFI(280)' },
                { ban_id: 131, ban_numero: '146', ban_nome: 'GUITTA CC LTDA(146)' },
                { ban_id: 132, ban_numero: '343', ban_nome: 'FFA SCMEPP LTDA.(343)' },
                { ban_id: 133, ban_numero: '279', ban_nome: 'CCR DE PRIMAVERA DO LESTE(279)' },
                { ban_id: 134, ban_numero: '335', ban_nome: 'BANCO DIGIO(335)' },
                { ban_id: 135, ban_numero: '349', ban_nome: 'AMAGGI S.A. CFI(349)' },
                { ban_id: 136, ban_numero: '278', ban_nome: 'GENIAL INVESTIMENTOS CVM S.A.(278)' },
                { ban_id: 137, ban_numero: '271', ban_nome: 'IB CCTVM S.A.(271)' },
                { ban_id: 138, ban_numero: '021', ban_nome: 'BCO BANESTES S.A.(021)' },
                { ban_id: 139, ban_numero: '246', ban_nome: 'BCO ABC BRASIL S.A.(246)' },
                { ban_id: 140, ban_numero: '292', ban_nome: 'BS2 DTVM S.A.(292)' },
                { ban_id: 141, ban_numero: '751', ban_nome: 'SCOTIABANK BRASIL(751)' },
                { ban_id: 142, ban_numero: '352', ban_nome: 'TORO CTVM LTDA(352)' },
                { ban_id: 143, ban_numero: '208', ban_nome: 'BANCO BTG PACTUAL S.A.(208)' },
                { ban_id: 144, ban_numero: '746', ban_nome: 'BCO MODAL S.A.(746)' },
                { ban_id: 145, ban_numero: '241', ban_nome: 'BCO CLASSICO S.A.(241)' },
                { ban_id: 146, ban_numero: '336', ban_nome: 'BCO C6 S.A.(336)' },
                { ban_id: 147, ban_numero: '612', ban_nome: 'BCO GUANABARA S.A.(612)' },
                { ban_id: 148, ban_numero: '604', ban_nome: 'BCO INDUSTRIAL DO BRASIL S.A.(604)' },
                { ban_id: 149, ban_numero: '505', ban_nome: 'BCO CREDIT SUISSE S.A.(505)' },
                { ban_id: 150, ban_numero: '329', ban_nome: 'QI SCD S.A.(329)' },
                { ban_id: 151, ban_numero: '196', ban_nome: 'FAIR CC S.A.(196)' },
                { ban_id: 152, ban_numero: '342', ban_nome: 'CREDITAS SCD(342)' },
                { ban_id: 153, ban_numero: '300', ban_nome: 'BCO LA NACION ARGENTINA(300)' },
                { ban_id: 154, ban_numero: '477', ban_nome: 'CITIBANK N.A.(477)' },
                { ban_id: 155, ban_numero: '266', ban_nome: 'BCO CEDULA S.A.(266)' },
                { ban_id: 156, ban_numero: '122', ban_nome: 'BCO BRADESCO BERJ S.A.(122)' },
                { ban_id: 157, ban_numero: '376', ban_nome: 'BCO J.P. MORGAN S.A.(376)' },
                { ban_id: 158, ban_numero: '348', ban_nome: 'BCO XP S.A.(348)' },
                { ban_id: 159, ban_numero: '473', ban_nome: 'BCO CAIXA GERAL BRASIL S.A.(473)' },
                { ban_id: 160, ban_numero: '745', ban_nome: 'BCO CITIBANK S.A.(745)' },
                { ban_id: 161, ban_numero: '120', ban_nome: 'BCO RODOBENS S.A.(120)' },
                { ban_id: 162, ban_numero: '265', ban_nome: 'BCO FATOR S.A.(265)' },
                { ban_id: 163, ban_numero: '007', ban_nome: 'BNDES(007)' },
                { ban_id: 164, ban_numero: '188', ban_nome: 'ATIVA S.A. INVESTIMENTOS CCTVM(188)' },
                { ban_id: 165, ban_numero: '134', ban_nome: 'BGC LIQUIDEZ DTVM LTDA(134)' },
                { ban_id: 166, ban_numero: '029', ban_nome: 'BANCO ITAÚ CONSIGNADO S.A.(029)' },
                { ban_id: 167, ban_numero: '243', ban_nome: 'BCO MÁXIMA S.A.(243)' },
                { ban_id: 168, ban_numero: '078', ban_nome: 'HAITONG BI DO BRASIL S.A.(078)' },
                { ban_id: 169, ban_numero: '355', ban_nome: 'ÓTIMO SCD S.A.(355)' },
                { ban_id: 170, ban_numero: '367', ban_nome: 'VITREO DTVM S.A.(367)' },
                { ban_id: 171, ban_numero: '373', ban_nome: 'UP.P SEP S.A.(373)' },
                { ban_id: 172, ban_numero: '111', ban_nome: 'OLIVEIRA TRUST DTVM S.A.(111)' },
                { ban_id: 173, ban_numero: '306', ban_nome: 'PORTOPAR DTVM LTDA(306)' },
                { ban_id: 174, ban_numero: '017', ban_nome: 'BNY MELLON BCO S.A.(017)' },
                { ban_id: 175, ban_numero: '174', ban_nome: 'PERNAMBUCANAS FINANC S.A. CFI(174)' },
                { ban_id: 176, ban_numero: '495', ban_nome: 'BCO LA PROVINCIA B AIRES BCE(495)' },
                { ban_id: 177, ban_numero: '125', ban_nome: 'PLURAL BCO BM(125)' },
                { ban_id: 178, ban_numero: '488', ban_nome: 'JPMORGAN CHASE BANK(488)' },
                { ban_id: 179, ban_numero: '065', ban_nome: 'BCO ANDBANK S.A.(065)' },
                { ban_id: 180, ban_numero: '492', ban_nome: 'ING BANK N.V.(492)' },
                { ban_id: 181, ban_numero: '145', ban_nome: 'LEVYCAM CCV LTDA(145)' },
                { ban_id: 182, ban_numero: '250', ban_nome: 'BCV(250)' },
                { ban_id: 183, ban_numero: '354', ban_nome: 'NECTON INVESTIMENTOS S.A CVM(354)' },
                { ban_id: 184, ban_numero: '253', ban_nome: 'BEXS CC S.A.(253)' },
                { ban_id: 185, ban_numero: '269', ban_nome: 'BCO HSBC S.A.(269)' },
                { ban_id: 186, ban_numero: '213', ban_nome: 'BCO ARBI S.A.(213)' },
                { ban_id: 187, ban_numero: '139', ban_nome: 'INTESA SANPAOLO BRASIL S.A. BM(139)' },
                { ban_id: 188, ban_numero: '018', ban_nome: 'BCO TRICURY S.A.(018)' },
                { ban_id: 189, ban_numero: '422', ban_nome: 'BCO SAFRA S.A.(422)' },
                { ban_id: 190, ban_numero: '630', ban_nome: 'SMARTBANK(630)' },
                { ban_id: 191, ban_numero: '224', ban_nome: 'BCO FIBRA S.A.(224)' },
                { ban_id: 192, ban_numero: '393', ban_nome: 'BCO VOLKSWAGEN S.A(393)' },
                { ban_id: 193, ban_numero: '600', ban_nome: 'BCO LUSO BRASILEIRO S.A.(600)' },
                { ban_id: 194, ban_numero: '390', ban_nome: 'BCO GM S.A.(390)' },
                { ban_id: 195, ban_numero: '623', ban_nome: 'BANCO PAN(623)' },
                { ban_id: 196, ban_numero: '655', ban_nome: 'BCO VOTORANTIM S.A.(655)' },
                { ban_id: 197, ban_numero: '479', ban_nome: 'BCO ITAUBANK S.A.(479)' },
                { ban_id: 198, ban_numero: '456', ban_nome: 'BCO MUFG BRASIL S.A.(456)' },
                { ban_id: 199, ban_numero: '464', ban_nome: 'BCO SUMITOMO MITSUI BRASIL S.A.(464)' },
                { ban_id: 200, ban_numero: '341', ban_nome: 'ITAÚ UNIBANCO S.A.(341)' },
                { ban_id: 201, ban_numero: '237', ban_nome: 'BCO BRADESCO S.A.(237)' },
                { ban_id: 202, ban_numero: '381', ban_nome: 'BCO MERCEDES-BENZ S.A.(381)' },
                { ban_id: 203, ban_numero: '613', ban_nome: 'OMNI BANCO S.A.(613)' },
                { ban_id: 204, ban_numero: '652', ban_nome: 'ITAÚ UNIBANCO HOLDING S.A.(652)' },
                { ban_id: 205, ban_numero: '637', ban_nome: 'BCO SOFISA S.A.(637)' },
                { ban_id: 206, ban_numero: '653', ban_nome: 'BCO INDUSVAL S.A.(653)' },
                { ban_id: 207, ban_numero: '069', ban_nome: 'BCO CREFISA S.A.(069)' },
                { ban_id: 208, ban_numero: '370', ban_nome: 'BCO MIZUHO S.A.(370)' },
                { ban_id: 209, ban_numero: '249', ban_nome: 'BANCO INVESTCRED UNIBANCO S.A.(249)' },
                { ban_id: 210, ban_numero: '318', ban_nome: 'BCO BMG S.A.(318)' },
                { ban_id: 211, ban_numero: '626', ban_nome: 'BCO C6 CONSIG(626)' },
                { ban_id: 212, ban_numero: '270', ban_nome: 'SAGITUR CC LTDA(270)' },
                { ban_id: 213, ban_numero: '366', ban_nome: 'BCO SOCIETE GENERALE BRASIL(366)' },
                { ban_id: 214, ban_numero: '113', ban_nome: 'MAGLIANO S.A. CCVM(113)' },
                { ban_id: 215, ban_numero: '131', ban_nome: 'TULLETT PREBON BRASIL CVC LTDA(131)' },
                { ban_id: 216, ban_numero: '011', ban_nome: 'C.SUISSE HEDGING-GRIFFO CV S/A(011)' },
                { ban_id: 217, ban_numero: '611', ban_nome: 'BCO PAULISTA S.A.(611)' },
                { ban_id: 218, ban_numero: '755', ban_nome: 'BOFA MERRILL LYNCH BM S.A.(755)' },
                { ban_id: 219, ban_numero: '089', ban_nome: 'CREDISAN CC(089)' },
                { ban_id: 220, ban_numero: '643', ban_nome: 'BCO PINE S.A.(643)' },
                { ban_id: 221, ban_numero: '140', ban_nome: 'EASYNVEST - TÍTULO CV SA(140)' },
                { ban_id: 222, ban_numero: '707', ban_nome: 'BCO DAYCOVAL S.A(707)' },
                { ban_id: 223, ban_numero: '288', ban_nome: 'CAROL DTVM LTDA.(288)' },
                { ban_id: 224, ban_numero: '363', ban_nome: 'SOCOPA SC PAULISTA S.A.(363)' },
                { ban_id: 225, ban_numero: '101', ban_nome: 'RENASCENCA DTVM LTDA(101)' },
                { ban_id: 226, ban_numero: '487', ban_nome: 'DEUTSCHE BANK S.A.BCO ALEMAO(487)' },
                { ban_id: 227, ban_numero: '233', ban_nome: 'BANCO CIFRA(233)' },
                { ban_id: 228, ban_numero: '177', ban_nome: 'GUIDE(177)' },
                { ban_id: 229, ban_numero: '365', ban_nome: 'SOLIDUS S.A. CCVM(365)' },
                { ban_id: 230, ban_numero: '633', ban_nome: 'BCO RENDIMENTO S.A.(633)' },
                { ban_id: 231, ban_numero: '218', ban_nome: 'BCO BS2 S.A.(218)' },
                { ban_id: 232, ban_numero: '169', ban_nome: 'BCO OLÉ CONSIGNADO S.A.(169)' },
                { ban_id: 233, ban_numero: '293', ban_nome: 'LASTRO RDV DTVM LTDA(293)' },
                { ban_id: 234, ban_numero: '285', ban_nome: 'FRENTE CC LTDA.(285)' },
                { ban_id: 235, ban_numero: '080', ban_nome: 'B&T CC LTDA.(080)' },
                { ban_id: 236, ban_numero: '753', ban_nome: 'NOVO BCO CONTINENTAL S.A. - BM(753)' },
                { ban_id: 237, ban_numero: '222', ban_nome: 'BCO CRÉDIT AGRICOLE BR S.A.(222)' },
                { ban_id: 238, ban_numero: '281', ban_nome: 'CCR COOPAVEL(281)' },
                { ban_id: 239, ban_numero: '754', ban_nome: 'BANCO SISTEMA(754)' },
                { ban_id: 240, ban_numero: '098', ban_nome: 'CREDIALIANÇA CCR(098)' },
                { ban_id: 241, ban_numero: '610', ban_nome: 'BCO VR S.A.(610)' },
                { ban_id: 242, ban_numero: '712', ban_nome: 'BCO OURINVEST S.A.(712)' },
                { ban_id: 243, ban_numero: '010', ban_nome: 'CREDICOAMO(010)' },
                { ban_id: 244, ban_numero: '283', ban_nome: 'RB CAPITAL INVESTIMENTOS DTVM LTDA.(283)' },
                { ban_id: 245, ban_numero: '033', ban_nome: 'BCO SANTANDER (BRASIL) S.A.(033)' },
                { ban_id: 246, ban_numero: '217', ban_nome: 'BANCO JOHN DEERE S.A.(217)' },
                { ban_id: 247, ban_numero: '041', ban_nome: 'BCO DO ESTADO DO RS S.A.(041)' },
                { ban_id: 248, ban_numero: '117', ban_nome: 'ADVANCED CC LTDA(117)' },
                { ban_id: 249, ban_numero: '654', ban_nome: 'BCO DIGIMAIS S.A.(654)' },
                { ban_id: 250, ban_numero: '371', ban_nome: 'WARREN CVMC LTDA(371)' },
                { ban_id: 251, ban_numero: '212', ban_nome: 'BANCO ORIGINAL(212)' },
                { ban_id: 252, ban_numero: '289', ban_nome: 'DECYSEO CC LTDA.(289)' }

            ],
            {}
        );

        await queryInterface.sequelize.query('select setval(\'spa2.banco_ban_id_seq\', coalesce(max(ban_id), 0)+1, false) from spa2.banco;');
    },

    down: (queryInterface, Sequelize) => queryInterface.bulkDelete(
        { tableName: 'banco', schema: 'spa2' },
        null,
        {}
    )
};
