'use strict';

module.exports = {
    up: async(queryInterface, Sequelize) => {
        await queryInterface.bulkInsert(
            { tableName: 'menu', schema: 'spa2' },
            [
                { men_id: 37, men_id_pai: null, men_nome: 'Home', men_url: '/home', tel_id: 22, versao: 0, mmu_id: 1, men_ordem_pai: 1, tel_interna: false },
                { men_id: 38, men_id_pai: null, men_nome: 'Processos', men_url: null, tel_id: 23, versao: 0, mmu_id: 1, men_ordem_pai: 2, tel_interna: false },
                { men_id: 46, men_id_pai: '38', men_nome: 'Criar novo', men_url: '/processo-cria', tel_id: 31, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 64, men_id_pai: null, men_nome: 'Home', men_url: '/home', tel_id: 22, versao: 0, mmu_id: 2, men_ordem_pai: 1, tel_interna: false },
                { men_id: 43, men_id_pai: null, men_nome: 'Manutenção', men_url: null, tel_id: 27, versao: 0, mmu_id: 1, men_ordem_pai: 7, tel_interna: false },
                { men_id: 328, men_id_pai: '43', men_nome: 'Tipos de processo', men_url: '/tipos-processo', tel_id: 397, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 344, men_id_pai: '43', men_nome: 'Fluxos', men_url: '/fluxos', tel_id: 413, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 282, men_id_pai: '43', men_nome: 'Telas', men_url: '/telas', tel_id: 337, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 63, men_id_pai: '43', men_nome: 'Gêneros', men_url: '/generos', tel_id: 343, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 61, men_id_pai: '43', men_nome: 'Áreas de menu', men_url: '/areas-menu', tel_id: 349, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 62, men_id_pai: '43', men_nome: 'Modelos de menus', men_url: '/modelo-menu', tel_id: 348, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 289, men_id_pai: '43', men_nome: 'Menus', men_url: '/menus', tel_id: 353, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 526, men_id_pai: '43', men_nome: 'Razões de trâmite', men_url: '/razao', tel_id: 623, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 527, men_id_pai: '43', men_nome: 'Setores', men_url: '/setores', tel_id: 624, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 528, men_id_pai: '43', men_nome: 'Lotações', men_url: '/lotacoes', tel_id: 625, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 529, men_id_pai: '43', men_nome: 'Tipos de manifestação', men_url: '/tipos-manifestacao', tel_id: 626, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 532, men_id_pai: '43', men_nome: 'Nodos', men_url: '/nodos', tel_id: 479, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 533, men_id_pai: '43', men_nome: 'Próximos trâmites', men_url: '/proximos-tramites', tel_id: 628, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 549, men_id_pai: '43', men_nome: 'Tipos de documento', men_url: '/tipos-documento', tel_id: 644, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 45, men_id_pai: '38', men_nome: 'Consultar', men_url: '/processo-consulta', tel_id: 30, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 65, men_id_pai: null, men_nome: 'Processos', men_url: null, tel_id: 23, versao: 0, mmu_id: 2, men_ordem_pai: 2, tel_interna: false },
                { men_id: 71, men_id_pai: '65', men_nome: 'Criar', men_url: '/processo-cria', tel_id: 31, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: false },
                { men_id: 70, men_id_pai: '65', men_nome: 'Consultar', men_url: '/processo-consulta', tel_id: 30, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: false },
                { men_id: 440, men_id_pai: null, men_nome: 'Dados processo', men_url: '/dados-processo', tel_id: 539, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 441, men_id_pai: null, men_nome: 'Dados processo', men_url: '/dados-processo', tel_id: 539, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 530, men_id_pai: null, men_nome: 'Criar manifestação', men_url: '/manifestacao-cria', tel_id: 627, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 531, men_id_pai: null, men_nome: 'Criar manifestação', men_url: '/manifestacao-cria', tel_id: 627, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 547, men_id_pai: null, men_nome: 'Tramitar', men_url: '/tramita', tel_id: 643, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 548, men_id_pai: null, men_nome: 'Tramitar', men_url: '/tramita', tel_id: 643, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 550, men_id_pai: null, men_nome: 'Criar manifestação executiva', men_url: '/manifestacao-cria-executiva', tel_id: 645, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 551, men_id_pai: null, men_nome: 'Criar manifestação executiva', men_url: '/manifestacao-cria-executiva', tel_id: 645, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 552, men_id_pai: null, men_nome: 'Criar visto', men_url: '/manifestacao-cria-visto', tel_id: 646, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 553, men_id_pai: null, men_nome: 'Criar visto', men_url: '/manifestacao-cria-visto', tel_id: 646, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 554, men_id_pai: null, men_nome: 'Criar ciência', men_url: '/manifestacao-cria-ciencia', tel_id: 648, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 555, men_id_pai: null, men_nome: 'Criar ciência', men_url: '/manifestacao-cria-ciencia', tel_id: 648, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 556, men_id_pai: null, men_nome: 'Criar ciência averbação', men_url: '/manifestacao-cria-ciencia-averbacao', tel_id: 650, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 557, men_id_pai: null, men_nome: 'Criar ciência averbação', men_url: '/manifestacao-cria-ciencia-averbacao', tel_id: 650, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 558, men_id_pai: null, men_nome: 'Criar averbação', men_url: '/manifestacao-cria-averbacao', tel_id: 649, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 559, men_id_pai: null, men_nome: 'Criar averbação', men_url: '/manifestacao-cria-averbacao', tel_id: 649, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 564, men_id_pai: null, men_nome: 'Criar aval horário', men_url: '/manifestacao-cria-aval-horario', tel_id: 651, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 565, men_id_pai: null, men_nome: 'Criar aval horário', men_url: '/manifestacao-cria-aval-horario', tel_id: 651, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 566, men_id_pai: null, men_nome: 'Criar contagem de tempo', men_url: '/manifestacao-cria-contagem-tempo', tel_id: 652, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 567, men_id_pai: null, men_nome: 'Criar contagem de tempo', men_url: '/manifestacao-cria-contagem-tempo', tel_id: 652, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 568, men_id_pai: null, men_nome: 'Criar ciência do cálculo', men_url: '/manifestacao-cria-ciencia-calculo', tel_id: 653, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 569, men_id_pai: null, men_nome: 'Criar ciência do cálculo', men_url: '/manifestacao-cria-ciencia-calculo', tel_id: 653, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 570, men_id_pai: 43, men_nome: 'Regras de aposentação', men_url: '/regras-aposentacao', tel_id: 654, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 571, men_id_pai: null, men_nome: 'Criar parecer Projuris aposentadoria', men_url: '/manifestacao-cria-parecer-projuris-aposentadoria', tel_id: 655, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 572, men_id_pai: null, men_nome: 'Criar parecer Projuris aposentadoria', men_url: '/manifestacao-cria-parecer-projuris-aposentadoria', tel_id: 655, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true },
                { men_id: 573, men_id_pai: null, men_nome: 'Home', men_url: '/home', tel_id: 22, versao: 0, mmu_id: 423, men_ordem_pai: null, tel_interna: false },
                { men_id: 574, men_id_pai: null, men_nome: 'Criar manifestação', men_url: '/manifestacao-cria', tel_id: 627, versao: 0, mmu_id: 423, men_ordem_pai: 0, tel_interna: true },
                { men_id: 575, men_id_pai: null, men_nome: 'Criar processo Pas Pad', men_url: '/processo-pas-pad', tel_id: 656, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 576, men_id_pai: 43, men_nome: 'Membros comissão', men_url: '/membros-comissao', tel_id: 657, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 577, men_id_pai: null, men_nome: 'Criar manifestação Pas / Pad', men_url: '/manifestacao-cria-pas-pad', tel_id: 658, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 578, men_id_pai: 43, men_nome: 'Sigilos', men_url: '/sigilos', tel_id: 659, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: false },
                { men_id: 580, men_id_pai: null, men_nome: 'Criar manifestação decisão PAD', men_url: '/manifestacao-cria-decisao-pad', tel_id: 660, versao: 0, mmu_id: 2, men_ordem_pai: null, tel_interna: true },
                { men_id: 584, men_id_pai: null, men_nome: 'Home', men_url: '/home', tel_id: 22, versao: 0, mmu_id: 3, men_ordem_pai: 1, tel_interna: false },
                { men_id: 585, men_id_pai: null, men_nome: 'Processos', men_url: null, tel_id: 23, versao: 0, mmu_id: 3, men_ordem_pai: 2, tel_interna: false },
                { men_id: 586, men_id_pai: null, men_nome: 'Dados processo', men_url: 'dados-processo', tel_id: 539, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: true },
                { men_id: 587, men_id_pai: null, men_nome: 'Criar manifestação', men_url: '/manifestacao-cria', tel_id: 627, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: true },
                { men_id: 588, men_id_pai: null, men_nome: 'Tramitar', men_url: '/tramita', tel_id: 643, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: true },
                { men_id: 589, men_id_pai: null, men_nome: 'GeraFluxo', men_url: '/gera-fluxo', tel_id: 647, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: true },
                { men_id: 592, men_id_pai: 585, men_nome: 'Consultar', men_url: '/processo-consulta', tel_id: 30, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: false },
                { men_id: 593, men_id_pai: null, men_nome: 'Criar ciência', men_url: '/manifestacao-cria-ciencia', tel_id: 648, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: true },
                { men_id: 594, men_id_pai: null, men_nome: 'Criar ciência averbação', men_url: '/manifestacao-cria-ciencia-averbacao', tel_id: 650, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: true },
                { men_id: 595, men_id_pai: null, men_nome: 'Criar ciência do cálculo', men_url: '/manifestacao-cria-ciencia-calculo', tel_id: 653, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: true },
                { men_id: 590, men_id_pai: 585, men_nome: 'Criar RH', men_url: '/processo-cria', tel_id: 31, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: false },
                { men_id: 591, men_id_pai: 585, men_nome: 'Execução de despesas', men_url: '/processo-execucao-despesa', tel_id: 661, versao: 0, mmu_id: 3, men_ordem_pai: null, tel_interna: false },
                { men_id: 596, men_id_pai: null, men_nome: 'Criar manifestação Pas / Pad', men_url: '/processo-pas-pad', tel_id: 656, versao: 0, mmu_id: 1, men_ordem_pai: null, tel_interna: true }
            ],
            {}
        );

        await queryInterface.sequelize.query('select setval(\'spa2.menu_men_id_seq\', coalesce(max(men_id), 0)+1, false) from spa2.menu;');
    },

    down: (queryInterface, Sequelize) => queryInterface.bulkDelete(
        { tableName: 'menu', schema: 'spa2' },
        null,
        {}
    )
};
