// Gêneros
export const GEN_REQUERIMENTOS_RH = 4;
export const GEN_BAIXA_BENS = 6;
export const GEN_EXECUCAO_DESPESAS = 7;
export const GEN_PRESIDENCIA = 29;
export const GEN_PRONTO_PAGAMENTO = 60;

// Tipos de processo
export const TPR_PAD = 15;
export const TPR_PAS = 16;
export const TPR_ABONO_PERMANENCIA = 17;
export const TPR_FOLHA_PAGAMENTO_GERAL = 18;
export const TPR_GRATIFICACAO_FORMACAO_ACADEMICA = 20;
export const TPR_AVERBACAO_TEMPO_SERVICO = 21;
export const TPR_AUXILIO_FUNERAL = 22;
export const TPR_APOSENTADORIA = 23;
export const TPR_DESCONTO_PENSAO_ALIMENTICIA = 25;
export const TPR_DEMAIS = 26;
export const TPR_NAO_PUBLICO = 27;
export const TPR_BAIXA_BENS = 28;
export const TPR_PRONTO_PAGAMENTO = 29;
export const TPR_EXECUCAO_DESPESAS = 30;
export const TPR_HORARIO_ESPECIAL_ESTUDANTE = 241;
export const TPR_REVISOES_RETROATIVOS = 242;
export const TPR_REVISAO_DESCONTO_PENSAO_ALIMENTICIA = 247;
export const TPR_RECURSO = 248;
export const TPR_RECURSO_REVISAO_PAD = 249;
export const TPR_APOSENTADORIA_INICIATIVA_ADM = 250;
export const TPR_AQUISICAO_BENS_SERVICOS = 251;

// Área
export const AREA_PRESIDENCIA = 88;
export const AREA_COMISSAO_EXECUTIVA = 398;
export const AREA_DPS = 32;
export const AREA_DARH = 7;
export const AREA_DCF = 168;
export const AREA_DAF = 4;
export const TODA_AREA = 556;
export const TODO_GABINETE = 557;
export const GAB_1_SECRETARIA = 98;
export const GAB_2_SECRETARIA = 100;
export const IPMC = 1500;
export const COMISSAO_PROCESSANTE = 2000;

// tipo de manifestação
export const TMN_ATESTO = 1;
export const TMN_INFORMACAO = 2;
export const TMN_PARECER = 3;
export const TMN_MANIFESTACAO_EXECUTIVA = 5;
export const TMN_MANIFESTACAO_PRESIDENCIA = 8;
export const TMN_CIENCIA_PROCESSO = 10;
export const TMN_MANIFESTACAO_AVERBACAO = 11;
export const TMN_CIENCIA_AVERBACAO = 12;
export const TMN_AVAL_HORARIO_ESPECIAL = 13;
export const TMN_CALCULO_TEMPO_SERVICO = 14;
export const TMN_CIENCIA_CALCULO_APOSENTADORIA = 15;
export const TMN_DISCORDANCIA_CALCULO = 16;
export const TMN_PARECER_LEGALIDADE_REGULARIDADE = 17;
export const TMN_CORRECAO_OU_ESCLARECIMENTOS = 18;
export const TMN_MANIFESTACAO_ORGAO_EXTERNO = 19;
export const TMN_DECISAO_PAD = 20;

// Tipo documento
export const TPD_DECISAO_TCE_LEGAL_ADMISSAO = 2;
export const TPD_CERTIDAO_TEMPO_CONTRIBUICAO = 3;
export const TPD_LAUDO_IPMC_INVALIDEZ = 4;
export const TPD_ATO_ADMINISTRATIVO = 5;
export const TPD_FICHA_FUNCIONAL = 6;
export const TPD_FICHA_FINANCEIRA = 7;
export const TPD_FICHA_CADASTRAL = 8;
export const TPD_CONTRACHEQUE = 9;
export const TPD_MINUTA_ATO_INATIVIDADE = 10;
export const TPD_MANIFESTACAO_TCE = 11;
export const TPD_CERTIDAO_ABONO_PERMANENCIA = 12;
export const TPD_OFICIO_JUDICIAL = 13;
export const TPD_DIPLOMA_GRADUACAO = 14;
export const TPD_DIPLOMA_POS = 15;
export const TPD_COMPROVANTE_MATRICULA = 16;
export const TPD_COMPROVANTE_INCOMPATIBILIDADE_HORARIO = 17;
export const TPD_COMPROVANTE_CONCLUSAO_CURSO = 18;
export const TPD_ATESTADO_OBITO = 19;
export const TPD_COMPROVANTE_DESPESA_FUNERAL = 20;
export const TPD_RG = 21;
export const TPD_CPF = 22;
export const TPD_DENUNCIA_IRREGULARIDADE = 23;
export const TPD_RELATORIO_FINAL_PAS = 24;
export const TPD_RELATORIO_FINAL_PAD = 25;
export const TPD_PRORROGACAO_PRAZO = 26;
export const TPD_AVAL_COMISSAO_EXECUTIVA = 27;
export const TPD_DECISAO_EXECUTIVA = 28;
export const TPD_MANIFESTACAO = 29;
export const TPD_VISTO_EXECUTIVA = 30;
export const TPD_CIENCIA_PROCESSO = 31;
export const TPD_AVERBACAO = 32;
export const TPD_CIENCIA_AVERBACAO = 33;
export const TPD_AVAL_HORARIO_ESPECIAL = 34;
export const TPD_CONTAGEM_TEMPO_SERVICO = 35;
export const TPD_CIENCIA_CALCULO_APOSENTADORIA = 36;
export const TPD_DISCORDANCIA_CALCULO = 37;
export const TPD_CAPA_PROCESSO = 38;
export const TPD_PARECER_PROJURIS_APOSENTADORIA = 39;
export const TPD_CORRECAO_INFORMACOES_ESCLARECIMENTOS = 40;
export const TPD_DECISAO_PAD = 41;
export const TPD_EXECUCAO_DESPESA = 54;

// Razões de trâmite
export const RAZ_ENCAMINHAMENTO = 82;
export const RAZ_VERIFICACAO = 105;
export const RAZ_CIENCIA = 106;
export const RAZ_ENCERRAMENTO = 107;
export const RAZ_NOVA_CTC = 116;
export const RAZ_CIENCIA_AVERBACAO = 117;
export const RAZ_AVAL_CONCESSAO = 118;
export const RAZ_CIENCIA_DECISAO = 119;
export const RAZ_DISCORDANCIA_CALCULO = 120;
export const RAZ_CORRECAO_INFORMACOES_ESCLARECIMENTOS = 121;
export const RAZ_ENVIO_TC = 122;
export const RAZ_NOVAS_DILIGENCIAS_OU_AGRAVAMENTO_PENALIDADE = 123;

// Fluxos
export const FLU_SINDICANCIA_ADMINISTRATIVA = 2;
export const FLU_PAD = 3;
export const FLU_REVISAO_PAD = 4;
export const FLU_ABONO_PERMANENCIA = 5;
export const FLU_DESCONTO_DETERMINACAO_JUDICIAL = 6;
export const FLU_FOLHA_PAGAMENTO_SERVIDORES_VEREADORES = 7;
export const FLU_GRATIFICACAO_ESTIMULO_FORMACAO_ACADEMICA = 9;
export const FLU_HORARIO_ESPECIAL_TRABALHO = 10;
export const FLU_INCORPORACAO_TEMPO_CONTRIBUICAO = 11;
export const FLU_DEMAIS = 12;
export const FLU_PAGAMENTO_AUXILIO_FUNERAL = 13;
export const FLU_RECURSO_PESSOAL = 14;
export const FLU_SOLICITACAO_APOSENTADORIA_VOLUNTARIA = 15;
export const FLU_CERTIDAO_TEMPO_CONTRIBUICAO_SERVICO = 16;
export const FLU_AQUISICAO_BENS = 17;
export const FLU_BAIXA_BENS = 18;
export const FLU_PRONTO_PAGAMENTO = 19;
export const FLU_SOLICITACAO_APOSENTADORIA_INICIATIVA_ADMINISTRACAO = 240;
