#Este workflow cria o ambiente, instala as dependências e verifica padrão de código através do lint

name: Frontend CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FRONTEND_DIR: ./frontend

    name: Testando no node 12.x
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      run: |
        node --version
        npm --version
        yarn --version
        yarn install --frozen-lockfile
      working-directory: ${{env.FRONTEND_DIR}}
      
