# Este workflow cria o ambiente, instala as dependências e verifica padrão de código através do lint

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
  
    container: node:10.18-jessie

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: yarn
      
    - name: Check linting
      run: yarn lint
    
