# Este workflow cria o ambiente, instala as dependências e verifica padrão de código através do lint

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BACKEND_DIR: ./backend

    name: Testando no node 12.x
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: yarn
      working-directory: ${{env.BACKEND_DIR}}
      
    - name: Check linting
      run: yarn lint
      working-directory: ${{env.BACKEND_DIR}}
